'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On
Imports System
Namespace My.Resources
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        Private resourceMan As Global.System.Resources.ResourceManager
        Private resourceCulture As Global.System.Globalization.CultureInfo
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SICyF.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Banco_Macro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Banco_Macro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property checkbox_circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkbox_circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property checkbox_cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkbox_cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property checkmark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property circled_equal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("circled_equal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property contaduria_logo_vect() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("contaduria_logo_vect", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property currency_dollar_sign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("currency_dollar_sign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hand_thumbsup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hand_thumbsup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_file_black_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_file_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_file_black_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_file_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_file_black_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_file_black_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_file_black_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_file_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_file_white_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_file_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_file_white_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_file_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_file_white_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_file_white_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_file_white_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_file_white_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_money_black_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_money_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_money_black_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_money_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_money_black_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_money_black_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_money_black_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_money_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_money_white_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_money_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_money_white_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_money_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_money_white_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_money_white_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_attach_money_white_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_money_white_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_all_black_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_all_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_all_black_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_all_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_all_black_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_all_black_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_all_black_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_all_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_all_white_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_all_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_all_white_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_all_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_all_white_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_all_white_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_all_white_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_all_white_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_bottom_black_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_bottom_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_bottom_black_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_bottom_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_bottom_black_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_bottom_black_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_bottom_black_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_bottom_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_bottom_white_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_bottom_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_bottom_white_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_bottom_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_bottom_white_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_bottom_white_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_bottom_white_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_bottom_white_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_clear_black_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_clear_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_clear_black_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_clear_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_clear_black_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_clear_black_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_clear_black_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_clear_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_clear_white_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_clear_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_clear_white_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_clear_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_clear_white_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_clear_white_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_clear_white_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_clear_white_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_color_black_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_color_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_color_black_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_color_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_color_black_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_color_black_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_color_black_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_color_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_color_white_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_color_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_color_white_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_color_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_color_white_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_color_white_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_color_white_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_color_white_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_horizontal_black_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_horizontal_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_horizontal_black_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_horizontal_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_horizontal_black_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_horizontal_black_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_horizontal_black_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_horizontal_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_horizontal_white_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_horizontal_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_horizontal_white_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_horizontal_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_horizontal_white_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_horizontal_white_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_horizontal_white_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_horizontal_white_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_inner_black_18dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_inner_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_inner_black_24dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_inner_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_border_inner_black_36dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_border_inner_black_36dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_receipt_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_receipt_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property ic_wrap_text_white_48dp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_wrap_text_white_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lock_closed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock_closed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_afip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_afip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_DGR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_DGR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property preloading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preloading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TRABAJANDO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TRABAJANDO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrabajandoGif1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrabajandoGif1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
